name: Build and publish
on: push

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_KEY }}
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: nix-shell --run build-component
      env:
        ENV: production
    - run: nix-shell --run publish-component
      if: github.ref == 'refs/heads/master'
      env:
        ENV: production
        SAS_TOKEN: ${{ secrets.SAS_TOKEN }}
